/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and reactivejob-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ReactiveJobListerExpansion allows custom methods to be added to
// ReactiveJobLister.
type ReactiveJobListerExpansion interface{}

// ReactiveJobNamespaceListerExpansion allows custom methods to be added to
// ReactiveJobNamespaceLister.
type ReactiveJobNamespaceListerExpansion interface{}
