/*
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and reactivejob-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	batchcssapcomv1alpha1 "github.com/sap/reactivejob-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ReactiveJobLister helps list Reactivejobs.
// All objects returned here must be treated as read-only.
type ReactiveJobLister interface {
	// List lists all Reactivejobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*batchcssapcomv1alpha1.ReactiveJob, err error)
	// Reactivejobs returns an object that can list and get Reactivejobs.
	Reactivejobs(namespace string) ReactiveJobNamespaceLister
	ReactiveJobListerExpansion
}

// reactiveJobLister implements the ReactiveJobLister interface.
type reactiveJobLister struct {
	listers.ResourceIndexer[*batchcssapcomv1alpha1.ReactiveJob]
}

// NewReactiveJobLister returns a new ReactiveJobLister.
func NewReactiveJobLister(indexer cache.Indexer) ReactiveJobLister {
	return &reactiveJobLister{listers.New[*batchcssapcomv1alpha1.ReactiveJob](indexer, batchcssapcomv1alpha1.Resource("reactivejob"))}
}

// Reactivejobs returns an object that can list and get Reactivejobs.
func (s *reactiveJobLister) Reactivejobs(namespace string) ReactiveJobNamespaceLister {
	return reactiveJobNamespaceLister{listers.NewNamespaced[*batchcssapcomv1alpha1.ReactiveJob](s.ResourceIndexer, namespace)}
}

// ReactiveJobNamespaceLister helps list and get Reactivejobs.
// All objects returned here must be treated as read-only.
type ReactiveJobNamespaceLister interface {
	// List lists all Reactivejobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*batchcssapcomv1alpha1.ReactiveJob, err error)
	// Get retrieves the ReactiveJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*batchcssapcomv1alpha1.ReactiveJob, error)
	ReactiveJobNamespaceListerExpansion
}

// reactiveJobNamespaceLister implements the ReactiveJobNamespaceLister
// interface.
type reactiveJobNamespaceLister struct {
	listers.ResourceIndexer[*batchcssapcomv1alpha1.ReactiveJob]
}
