/*
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and reactivejob-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	batchcssapcomv1alpha1 "github.com/sap/reactivejob-operator/api/v1alpha1"
	scheme "github.com/sap/reactivejob-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ReactivejobsGetter has a method to return a ReactiveJobInterface.
// A group's client should implement this interface.
type ReactivejobsGetter interface {
	Reactivejobs(namespace string) ReactiveJobInterface
}

// ReactiveJobInterface has methods to work with ReactiveJob resources.
type ReactiveJobInterface interface {
	Create(ctx context.Context, reactiveJob *batchcssapcomv1alpha1.ReactiveJob, opts v1.CreateOptions) (*batchcssapcomv1alpha1.ReactiveJob, error)
	Update(ctx context.Context, reactiveJob *batchcssapcomv1alpha1.ReactiveJob, opts v1.UpdateOptions) (*batchcssapcomv1alpha1.ReactiveJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, reactiveJob *batchcssapcomv1alpha1.ReactiveJob, opts v1.UpdateOptions) (*batchcssapcomv1alpha1.ReactiveJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*batchcssapcomv1alpha1.ReactiveJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*batchcssapcomv1alpha1.ReactiveJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *batchcssapcomv1alpha1.ReactiveJob, err error)
	ReactiveJobExpansion
}

// reactivejobs implements ReactiveJobInterface
type reactivejobs struct {
	*gentype.ClientWithList[*batchcssapcomv1alpha1.ReactiveJob, *batchcssapcomv1alpha1.ReactiveJobList]
}

// newReactivejobs returns a Reactivejobs
func newReactivejobs(c *BatchV1alpha1Client, namespace string) *reactivejobs {
	return &reactivejobs{
		gentype.NewClientWithList[*batchcssapcomv1alpha1.ReactiveJob, *batchcssapcomv1alpha1.ReactiveJobList](
			"reactivejobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *batchcssapcomv1alpha1.ReactiveJob { return &batchcssapcomv1alpha1.ReactiveJob{} },
			func() *batchcssapcomv1alpha1.ReactiveJobList { return &batchcssapcomv1alpha1.ReactiveJobList{} },
		),
	}
}
