/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and reactivejob-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/sap/reactivejob-operator/api/v1alpha1"
	scheme "github.com/sap/reactivejob-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ReactiveJobsGetter has a method to return a ReactiveJobInterface.
// A group's client should implement this interface.
type ReactiveJobsGetter interface {
	ReactiveJobs(namespace string) ReactiveJobInterface
}

// ReactiveJobInterface has methods to work with ReactiveJob resources.
type ReactiveJobInterface interface {
	Create(ctx context.Context, reactiveJob *v1alpha1.ReactiveJob, opts v1.CreateOptions) (*v1alpha1.ReactiveJob, error)
	Update(ctx context.Context, reactiveJob *v1alpha1.ReactiveJob, opts v1.UpdateOptions) (*v1alpha1.ReactiveJob, error)
	UpdateStatus(ctx context.Context, reactiveJob *v1alpha1.ReactiveJob, opts v1.UpdateOptions) (*v1alpha1.ReactiveJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ReactiveJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ReactiveJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReactiveJob, err error)
	ReactiveJobExpansion
}

// reactiveJobs implements ReactiveJobInterface
type reactiveJobs struct {
	client rest.Interface
	ns     string
}

// newReactiveJobs returns a ReactiveJobs
func newReactiveJobs(c *BatchV1alpha1Client, namespace string) *reactiveJobs {
	return &reactiveJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the reactiveJob, and returns the corresponding reactiveJob object, and an error if there is any.
func (c *reactiveJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReactiveJob, err error) {
	result = &v1alpha1.ReactiveJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reactivejobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ReactiveJobs that match those selectors.
func (c *reactiveJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReactiveJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ReactiveJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reactivejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested reactiveJobs.
func (c *reactiveJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("reactivejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a reactiveJob and creates it.  Returns the server's representation of the reactiveJob, and an error, if there is any.
func (c *reactiveJobs) Create(ctx context.Context, reactiveJob *v1alpha1.ReactiveJob, opts v1.CreateOptions) (result *v1alpha1.ReactiveJob, err error) {
	result = &v1alpha1.ReactiveJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("reactivejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(reactiveJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a reactiveJob and updates it. Returns the server's representation of the reactiveJob, and an error, if there is any.
func (c *reactiveJobs) Update(ctx context.Context, reactiveJob *v1alpha1.ReactiveJob, opts v1.UpdateOptions) (result *v1alpha1.ReactiveJob, err error) {
	result = &v1alpha1.ReactiveJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reactivejobs").
		Name(reactiveJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(reactiveJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *reactiveJobs) UpdateStatus(ctx context.Context, reactiveJob *v1alpha1.ReactiveJob, opts v1.UpdateOptions) (result *v1alpha1.ReactiveJob, err error) {
	result = &v1alpha1.ReactiveJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reactivejobs").
		Name(reactiveJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(reactiveJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the reactiveJob and deletes it. Returns an error if one occurs.
func (c *reactiveJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reactivejobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *reactiveJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reactivejobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched reactiveJob.
func (c *reactiveJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReactiveJob, err error) {
	result = &v1alpha1.ReactiveJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("reactivejobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
