---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-cs-sap-com-v1alpha1-reactivejob
  failurePolicy: Fail
  name: mreactivejob.kb.io
  rules:
  - apiGroups:
    - batch.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - reactivejobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-cs-sap-com-v1alpha1-reactivejob
  failurePolicy: Fail
  name: vreactivejob.kb.io
  rules:
  - apiGroups:
    - batch.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - reactivejobs
  sideEffects: None
