# permissions for end users to edit reactivejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reactivejob-editor-role
rules:
- apiGroups:
  - batch.cs.sap.com
  resources:
  - reactivejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.cs.sap.com
  resources:
  - reactivejobs/status
  verbs:
  - get
