/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and reactivejob-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisbatchcssapcomv1alpha1 "github.com/sap/reactivejob-operator/api/v1alpha1"
	versioned "github.com/sap/reactivejob-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/reactivejob-operator/pkg/client/informers/externalversions/internalinterfaces"
	batchcssapcomv1alpha1 "github.com/sap/reactivejob-operator/pkg/client/listers/batch.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ReactiveJobInformer provides access to a shared informer and lister for
// Reactivejobs.
type ReactiveJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() batchcssapcomv1alpha1.ReactiveJobLister
}

type reactiveJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewReactiveJobInformer constructs a new informer for ReactiveJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewReactiveJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredReactiveJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredReactiveJobInformer constructs a new informer for ReactiveJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredReactiveJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BatchV1alpha1().Reactivejobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BatchV1alpha1().Reactivejobs(namespace).Watch(context.TODO(), options)
			},
		},
		&apisbatchcssapcomv1alpha1.ReactiveJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *reactiveJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredReactiveJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *reactiveJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisbatchcssapcomv1alpha1.ReactiveJob{}, f.defaultInformer)
}

func (f *reactiveJobInformer) Lister() batchcssapcomv1alpha1.ReactiveJobLister {
	return batchcssapcomv1alpha1.NewReactiveJobLister(f.Informer().GetIndexer())
}
